Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GuardClause:
  Exclude:
    - './*.gemspec'

Metrics/BlockLength:
  Exclude:
    - './*.gemspec'

Metrics/LineLength:
  Exclude:
    - './*.gemspec'

Metrics/AbcSize:
  Exclude:
    - 'test/colissimo_fuel_adjustment_coefficients_test.rb'
