Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GuardClause:
  Exclude:
    - './*.gemspec'
  
Metrics/BlockLength:
  Exclude:
    - './*.gemspec'

Metrics/LineLength:
  Exclude:
    - './*.gemspec'

