---
sudo: false

language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

os:
  - linux
  - osx

cache:
  bundler: true

before_install:
  - gem install bundler -v 1.17.1

script:
  - bundle install
  - bundle exec rake test
